services:
  app:
    image: ghcr.io/upcraftlp/s3-fileserver-rs:main
    restart: unless-stopped
    depends_on:
      - redis
    environment:
      REDIS_URL: redis://redis:6379
    env_file:
      - run/.env
    networks:
      - redis
    ports:
      - "3001:3001"
  redis:
    image: redis:alpine
    command: ["redis-server", "--save", "60", "1", "--loglevel", "warning"]
    restart: unless-stopped
    volumes:
      - redis-cache:/data
    networks:
      - redis

volumes:
  redis-cache:
    driver: local

networks:
  redis: {}
