services:
  redis:
    image: redis:alpine
    container_name: redis
    stdin_open: true
    tty: true
    ports:
      - "6379:6379"
    volumes:
      - ./run/.redis-data:/data
    restart: on-failure
